// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiJdzNiH-1ffGyh28636WKwPsx8lgj9YQ',
    appId: '1:468946443064:web:476b419a69eb971e31ffcd',
    messagingSenderId: '468946443064',
    projectId: 'camionappllication',
    authDomain: 'camionappllication.firebaseapp.com',
    storageBucket: 'camionappllication.firebasestorage.app',
    measurementId: 'G-7J8Y5BP2N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOVLF8c-Aw5_Wvg_hNCBvK9tU7jb-RQ0A',
    appId: '1:468946443064:android:f90255886add6a0b31ffcd',
    messagingSenderId: '468946443064',
    projectId: 'camionappllication',
    storageBucket: 'camionappllication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABhN98wsaLoDr-rWm6F9zwGSsxgT1EZ_s',
    appId: '1:468946443064:ios:7fcf80fb58c0fd0f31ffcd',
    messagingSenderId: '468946443064',
    projectId: 'camionappllication',
    storageBucket: 'camionappllication.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMobileCamion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABhN98wsaLoDr-rWm6F9zwGSsxgT1EZ_s',
    appId: '1:468946443064:ios:7fcf80fb58c0fd0f31ffcd',
    messagingSenderId: '468946443064',
    projectId: 'camionappllication',
    storageBucket: 'camionappllication.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMobileCamion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiJdzNiH-1ffGyh28636WKwPsx8lgj9YQ',
    appId: '1:468946443064:web:9272171c6f5510a231ffcd',
    messagingSenderId: '468946443064',
    projectId: 'camionappllication',
    authDomain: 'camionappllication.firebaseapp.com',
    storageBucket: 'camionappllication.firebasestorage.app',
    measurementId: 'G-QY8TC329E8',
  );
}
